---
title: "test"
author: "David Hrabovszki"
date: "3/6/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r warning=FALSE}
############# QUESTION 1 ##############
# R version
RNGversion('3.5.1')

#1

f <- function(x){
  return(x^2/exp(x) - 2*exp(-1*(9*sin(x)) / (x^2 + x + 1)))
}




#2

crossover <- function(x,y){
  return((x+y) / 2)
}


#3
mutate <- function(x){
  return(x^2 %% 30)
}

#4
genetic <- function(maxiter, mutprob){
  #a
  plot(x = seq(0,30, by=0.1), y = f(seq(0,30, by=0.1)), 
       type = "l", xlab = "x", ylab = "f(x)", main = paste("maxiter:",maxiter,"mutprob:",mutprob))
  abline(v=seq(0,30, by = 0.1)[which.max(f(seq(0,30,by = 0.1)))], col="blue" )
  #maximum value: f(1.2) = 0.234
  
  #b
  X = seq(0,30,5)
  
  #c
  Values = f(X)
  
  #d
  #set seed
  set.seed(1234567890)
  max=-Inf
  for (i in 1:maxiter) {
    #i
    parents = match(sample(X, 2),X)
    
    #ii
    victim = order(Values)[1]
    
    #iii
    kid = crossover(X[parents[1]],X[parents[2]])
    p = runif(1)
    if (p < mutprob) {
      kid = mutate(kid)
    }
    
    #iv
    X[victim] = kid
    Values = f(X)
    
    #v
    max = max(Values)
  }
  
  #e
  points(x = X, y = Values, col = "red", pch = 19)
  return(max)
}

```


```{r fig2, fig.height = 10, fig.width = 10}


max_values = data.frame(matrix(nrow = 3, ncol = 2))
par(mfrow=c(3,2))
max_values[1,1] = genetic(10,0.1)
max_values[1,2] = genetic(100,0.1)
max_values[2,1] = genetic(10,0.5)
max_values[2,2] = genetic(100,0.5)
max_values[3,1] = genetic(10,0.9)
max_values[3,2] = genetic(100,0.9)

rownames(max_values) = c("mutprob 0.1","mutprob 0.5","mutprob 0.9")
colnames(max_values) = c("maxiter 10","maxiter 100")
```

```{r}
knitr::kable(max_values, caption = 'Maximum values')
```

